### ISSUE TITLE
ConcurrentModificationException in handleGistError

### ISSUE THREAD

**Issue by ben-lotze** [customerio/gist-android#13]
We use the Flutter SDK in our app:
```yaml
customer_io: ^1.2.3
```

We got reported Exceptions from a concurrent modification on the native Android side:

```
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:831)
       at io.customer.messaginginapp.gist.presentation.GistSdk.handleGistError$messaginginapp_release(GistSdk.java)
       at io.customer.messaginginapp.gist.presentation.GistView.error(SourceFile)
       at io.customer.messaginginapp.gist.presentation.engine.EngineWebView$setupTimeout$1.run(SourceFile)
       at java.util.TimerThread.mainLoop(Timer.java:555)
       at java.util.TimerThread.run(Timer.java:505)
```

And
```
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at build.gist.presentation.GistSdk.handleGistError$gist_release(GistSdk.java:17)
       at build.gist.presentation.GistView.error(:7)
       at build.gist.presentation.engine.EngineWebView$setupTimeout$1.run(:24)
       at java.util.TimerThread.mainLoop(Timer.java:555)
       at java.util.TimerThread.run(Timer.java:505)
```

And 
```
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:831)
       at build.gist.presentation.GistSdk.handleGistError$gist_release(SourceFile)
       at build.gist.presentation.GistView.error(SourceFile)
       at build.gist.presentation.engine.EngineWebView$setupTimeout$1.run(SourceFile)
       at java.util.TimerThread.mainLoop(Timer.java:555)
       at java.util.TimerThread.run(Timer.java:505)
```

---

It seems to originate from here in the code: 
- `gist-android/gist/src/main/java/build/gist/presentation/GistSdk.kt `
- [github link to handleGistError](https://github.com/customerio/gist-android/blob/fb1532fd67665b152c656903e85b8740f4086af8/gist/src/main/java/build/gist/presentation/GistSdk.kt#L222C5-L224C5)

--- 

Severeness of the issue:
- Crashlytics shows event type "Crash", so the complete app was terminated for affected users. 
- But for some users who have this crash, I can find event logs in Customer IO, so it seems to be not happening every time.
- We have around 5.4k crashes and 4.8k affected users for above crashes.

---

Reported devices:
- 35% Motorola
  - 3% Moto G(60)
  - 3% Moto E5 Play
  - 2% Moto G(20)
  - 27% Other (33)
- 23% Xiaomi
  - 8% Redmi 9A
  - 3% Redmi Note 8
  - 2% Redmi 9C
  - 10% Other (12)
- 21% Huawei
  - 6% Y9 Prime 2019
  - 3% Huawei Y9 2019
  - 3% Huawei P30 Lite
  - 9% Other (11)
- 10% Samsung
  - 1% Galaxy A10
  - <1% Galaxy J4 Core
  - <1% Galaxy A23
  - 8% Other (15)
- 11% Other (5)
  - 10% ZTE 
  - 2% TCT Mobile Limited (Alcatel)
  - 1% Oppo 
  - <1% LGE
  - <1% Hisense
  - <1% Vivo

**Comment by BernardGatt** [comment]
Closing issue, for reference please see: https://github.com/customerio/customerio-android/issues/245
